name: Enforce Git Flow

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  enforce-gitflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check Git Flow Rules
        uses: actions/github-script@v7
        with:
          script: |
            const { context } = github;
            const pr = context.payload.pull_request;
            
            // Rule: Feature branches should target develop, not main
            if (pr.head.ref.startsWith('feature/') && pr.base.ref === 'main') {
              const message = `
              ❌ **Git Flow Violation**
              
              Feature branches cannot target \`main\` directly!
              
              **Required Flow:**
              \`\`\`
              feature/* → develop → staging → main
              \`\`\`
              
              **To fix this:**
              1. Change the base branch of this PR to \`develop\`
              2. Or use: \`gh pr edit ${pr.number} --base develop\`
              
              See CLAUDE.md for full git flow documentation.
              `;
              
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: message
              });
              
              // Set PR to draft and add error label
              await github.rest.pulls.update({
                ...context.repo,
                pull_number: pr.number,
                draft: true
              });
              
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: pr.number,
                labels: ['git-flow-violation']
              });
              
              core.setFailed('Git flow violation: feature branch targeting main');
            }
            
            // Rule: Only staging should target main
            if (pr.base.ref === 'main' && pr.head.ref !== 'staging') {
              const message = `
              ❌ **Git Flow Violation**
              
              Only \`staging\` branch can create PRs to \`main\`!
              
              Current: \`${pr.head.ref}\` → \`main\`
              
              **Required Flow:**
              \`\`\`
              feature/* → develop → staging → main
              \`\`\`
              
              Please follow the proper git flow documented in CLAUDE.md.
              `;
              
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: message
              });
              
              core.setFailed('Git flow violation: non-staging branch targeting main');
            }
            
            // Success message for correct flow
            if (pr.head.ref.startsWith('feature/') && pr.base.ref === 'develop') {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: pr.number,
                body: '✅ **Git Flow Correct**: Feature branch properly targeting `develop`'
              });
            }